project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1  110426"
        href: "HO_EX01.html"
      - text: "Hands-on Exercise 2  180426"
        href: "HO_EX02.html"
      - text: "Hands-on Exercise 3 Part 1  250426"
        href: "HO_EX03_1.html"        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

