---
title: "ISSS608-VAA"
---

### **Welcome to ISSS608 Visual Analytics and Application :)**

Here's documenting my course journey:

::: {.callout collapse="true" title="▶ Lesson 1: Introduction to Visual Analytics"}
- Motivation of Visual Analytics

- What Visual Analytics is

- Visual Analytics in History

- Intents of Visual Analytics Applications

- Visual Analytics Techniques: basic graphical methods

- Visual Analytics Tools
:::

::: {.callout collapse="true" title="▶ Lesson 2: Designing Graphs to Enlighten "}
- Human perception and information processing

- Perceptual and design principles for effective visual analytics

- Principles of Graphic Design

  - Rules for Encoding Values in Graph

  - JunkCharts

  - Practical Guides for Using Colour in Charts

  - Data-ink
:::

::: {.callout collapse="true" title="▶ Lesson 3: Interactivity in Visual Analytics: Principles and Methods"}
- Different types of interaction techniquee

- The role of Interaction in visual analytics

- The concept of linked multiple views

- Interactive analytics best practices
:::

::: {.callout collapse="true" title="▶ Lesson 4: Fundamentals of Visual Analytics"}
- Visual Analytics for Knowledge Discovery

- Visual Analytics Approach for Statistical Testing

- Visual Analytics for Building Better Models

- Visualising Uncertainty

  - Why Visualising Uncertainty?

  - Basic Statistical Concepts Related to Uncertainty

  - Univariate Graphical Methods for Visualising Uncertainty

    - Error bars

    - Confidence strips

    - Ridge plot

  - Bivariate Graphical Methods for Visualising Uncertainty

    - Funnel plot

- Variation and Its Discontents
:::

::: {.callout collapse="true" title="▶ Lesson 5: Visual Multivariate Analysis"}
- Correlation Matrix

  - Correlogram

- Multivariate Data Visualisation

  - ternary plot

  - Glyphs or Star Plot

  - heatmap

  - parallel coordinate plot

  - parallel plot

- Space-constrained visualization of hierarchies

  - Treemaps

  - Sunburst diagram
:::

::: {.callout collapse="true" title="▶ Lesson 7a: Visualising and Analysing Network Data"}
- Introduction to Graph Data Visualisation
  - Basic principles of network graph
  - Graph data visualisation in actions
- Network Graph Data
  - Network data sets
  - Graph data format
  - Graph Database
- Network Graph Visualisation Tools
- Designer toolkit
  - Gephi
- Programmer toolkit
  - R packages
- Graph layouts
  - Node-and-link layouts
  - Force-directed layout
  - Node-only layout
  - Adjacency matrix
- Visual Attributes
  - Key node attributes
  - Key edge attributes
  - Bundles, shapes, images, and more
- Visual Analysis of Network Graphs
  - Relationships
  - Hierarchies
  - Communities
- Flows
- Spatial networks
:::

::: {.callout collapse="true" title="▶ Lesson 7b: Visualising and Analysing Text Data"}
- Introduction to text data and text visualisation
- Text Visualisation methods:
  - Tag Cloud
  - Wordle
  - Word Tree
  - Phrase Nets
- Text Visualisation in R
  - textplot
  - LDAVis
  - quanteda
:::
